name: Arm-ttk Validations

on: [pull_request]

jobs:
  run-arm-ttk:
    runs-on: ubuntu-latest
    outputs:
      solutionName: ${{ steps.step1.outputs.solutionName }}
      mainTemplateChanged: ${{ steps.step1.outputs.mainTemplateChanged }}
      createUiChanged: ${{ steps.step1.outputs.createUiChanged }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - shell: pwsh
        id: step1
        name: Identify Changes in PR
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml
          ./.script/package-automation/arm-ttk-tests.ps1

      - uses: docker/build-push-action@v2
        id: publishGithubPackage
        name: Run ARM-TTK
        if: ${{ success() && steps.step1.outcome == 'success' && steps.step1.outputs.solutionName != '' && (steps.step1.outputs.mainTemplateChanged == 'true' || steps.step1.outputs.createUiChanged == 'true') }}
        env: 
          SolutionName: ${{ steps.step1.outputs.solutionName }}
          mainTemplateChanged: ${{ steps.step1.outputs.mainTemplateChanged }}
          createUiChanged: ${{ steps.step1.outputs.createUiChanged }}
        with:
          context: .
          file: ./.github/actions/Dockerfile
          push: false
          build-args: |
            SolutionName
            mainTemplateChanged
            createUiChanged
